version: '3'
services:
  web:
    image: "node:10"
    entrypoint:
      - "sh"
      - "-c"
      - "npm install && ./node_modules/.bin/nodemon server.js"
    working_dir: "/usr/src/app"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - ".:/usr/src/app"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
